### ISSUE TITLE
hi problem wifi

### ISSUE THREAD

**Issue by oremic** [ageorgios/esp-homekit-motor#3]
With this method everything works only if you connect to the wifi.
If there is no wifi does not allow you to open the normal shutter. ??
thanks

**Comment by ageorgios** [comment]
https://github.com/ageorgios/esp-homekit-motor/blob/79e7fc324ad9f05741744d7398ce8c1ab26d852d/esp-homekit-motor.c#L47

here are the gpios that are connected to buttons
